# Generated by Django 2.0.2 on 2019-01-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', '-title'], 'verbose_name': 'pagina', 'verbose_name_plural': 'paginas'},
        ),
    ]
